#!/usr/bin/env python
import os
from subprocess import call

cwd = os.getcwd()

if call(["python", cwd + "/git_assets/pre-push-runner.py"]) == 0:
  exit(0)
else:
  exit(1)



# #!/bin/bash
# illist_path='/Users/kaganmoshe/repos/illist'
# cd $illist_path
#
# ./git/pre-push-runner.sh
# runner_result=$?
#
# if [ "$runner_result" = 0 ]; then
#     exit 0
# else
#     exit 1
# fi
